export function createInitialEarthState() {
    return {
        events: [],
        filtered: [],
        clusters: [],
        selectedId: null,
        night: true,
        recentRingIds: [],
        captureMode: false,
        brandPreset: false,
        guide916: false,
        categoryCatalog: [],
        reelRecording: false,
        reelDurationSec: 8,
        motionPreset: 'slowOrbit',
        motionOffsetY: 0,
        todayLeadId: null,
        todayHighlightIds: [],
        realClouds: false,
        realCloudDate: null,
        cloudSourceState: 'artistic',
        cloudSourceMessage: 'Clouds: artistic procedural layer',
        dataSourceMode: 'eonet',
        dataSourceState: 'on',
        dataSourceMessage: 'Data source: NASA EONET default',
        usgsQuakes: false,
        firmsWildfires: false,
        auroraLayer: false,
        issLayer: false,
        airglowLayer: false,
        airglowPreset: 'scientific',
        airglowIntensity: 1.0,
        zodiacalLight: false,
        zodiacalIntensity: 1.0,
        noctilucentClouds: false,
        noctilucentPreset: 'scientific',
        noctilucentIntensity: 1.0,
        spinFast: 6.0,
        snapDuration: 0.45,
        reelMood: 'cinematic',
        earthLook: 'cinematic',
        atmosphereMode: 'physical',
        oceanFresnel: true,
        sssIce: true,
        materialMode: 'phong',
        socialPreset: 'custom',
        verticalDirector: false,
        captionStyle: 'cinematic',
        poeticCaptions: false,
        dataRhythm: true,
        includeIssBeat: false,
        dataRhythmPulseAmp: 1,
        dataRhythmDriftAmp: 1
    };
}

export const lookDefaults = {
    toneExposure: 1.04,
    bloomStrength: 0.34,
    bloomRadius: 0.72,
    bloomThreshold: 0.3,
    focusDuration: 1.45
};
